pipeline:
  build:
    image: runmymind/docker-android-sdk
    secrets: [KEY_STORE, ANDROID_STORE_FILE, ANDROID_STORE_PASSWORD, ANDROID_KEY_ALIAS, ANDROID_KEY_PASSWORD]
    commands:
    - bash ./gradlew assembleDebug check;

branches:
  exclude: [ l10n_alpha2 ]
